'🔑 socials':
  - any: ['packages/socials/**']

'🔒 core':
  - any: ['packages/core/**']

'🌐 oauth2':
  - any: ['packages/oauth2/**']

'💨 auth0':
  - any: ['packages/auth0/**']

'💠 credentials':
  - any: ['packages/credentials/**']
